### ISSUE TITLE
Set up wiki pages

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/contrib#1]
I'd love to have our goals written down in one place, our teams listed, and some welcome text outlined on the wiki as a public resource.

**Comment by cleverington** [comment]
It might be prudent to have team members indicate whether they are/could be Mentors for the project as well.

As the Composer workflow is "new and scary" for many, knowing whom to reach out to would be helpful on d8 projects.

**Comment by sparklingrobots** [comment]
This is a duplicate of #18 at this point, so I am going to mark closed.
