### ISSUE TITLE
Test conversion tickets summary

### ISSUE THREAD

**Issue by zenlan** [drupaldiversity/contrib#10]
[Remaining conversions per module](https://www.drupal.org/node/2735005 )

Of the 20 tickets listed on the above page...

* 5 - Need review
* 2 - Reviewed & tested by the community
* 7 - Postponed
* 3 - Need Work
* 3 - Active

The 5 "Need review" issues are either just about solved or have something going on that requires more than just a simple refactoring. Which leaves the 3 "Active" tickets. 

This one is unassigned and marked 'novice' with just the 2 Web tests to convert.
[Convert web tests to browser tests for quickedit module](https://www.drupal.org/node/2870458 )

This one is unassigned and has 6 tests - 4 Js and 2 Web.
[Convert web tests to browser tests for taxonomy module Part -2](https://www.drupal.org/node/2887134)

This is the big one, but it is just an umbrella that holds a summary of the system test tickets.
[Convert system functional tests to phpunit](https://www.drupal.org/node/2862508)
All of those sub-tickets are assigned and either closed or in review or marked as "hard".

All of the above require working in Drupal 8.5.x-dev. Anyone know what level of pain we can expect to get that set up? I'll give it a go although if its going to chew up half a day or something then tbh I'd rather be spending time building something, as much as I love tests and all.

Any thoughts?

**Comment by Caralin** [comment]
not sure about test setup but 'normally' setting up a clean 8.x works pretty well - 8.x upgrades can break badly

**Comment by NickDickinsonWilde** [comment]
I haven't got a 8.5 going yet (gotta do it soon to make sure no module breakages). But I can say most test conversion is quite easy. I converted all the tests in Advanced Aggregates 8.x-2.x to PHPUnit for my 8.x-3.x branch. So I can help anyone etc

**Comment by zenlan** [comment]
[Issues tagged with "phpunit+initiative"](https://www.drupal.org/project/issues/search?text=&projects=&assigned=&submitted=&project_issue_followers=&status%5B%5D=1&issue_tags_op=%3D&issue_tags=phpunit+initiative)
