### ISSUE TITLE
Agenda for 10/24 Back End Meeting

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/contrib#11]
Topics: 
--Should we look for other testing issues outside of the phpunit initiative (https://github.com/drupaldiversity/contrib/issues/10)
--mdrummond proposed this way of working: A) identify issues to work with, B) set up a group of 2-3 people to work on each issue *together*. Someone who understands tests can help guide somebody else as to how to approach the issue, what things to look at *without writing the code themselves.* The mentee is the one who actually writes the patch. Then at least one other person whose job is to test the issue to see if it works and post that on issue. If that person feels comfortable they can also do code review on the issue or the mentor can do that. Then all work together to get issue to RTBC.
--updates on resources gathered by angelam, caralin, nickwilde

Additional topics welcome! Just leave a comment here. 

If you can't make the meeting, leave your thoughts in a comment here as well so we can take your opinions into account.

**Comment by zenlan** [comment]
--Repo FAQ - how to get added, when to pr or fork, how to get a setting changed, who does what etc..
--Repo community profile - licence/templates

**Comment by sparklingrobots** [comment]
CoC discussion.

**Comment by sparklingrobots** [comment]
Meeting notes are here: https://github.com/drupaldiversity/contrib/blob/master/meeting-notes/back-end/2017.10.24.md
