### ISSUE TITLE
Review notes & resources and compile into a wiki

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/contrib#18]
@AlannaBurke offered to look over all of our notes and resources and try to compile it into a wiki. 

Just for reference: 
https://github.com/mdrummond/Writing-Tests-for-Drupal
https://docs.google.com/document/d/1vI37_UMC59yTXLqBE6zXX7gvBdzTpcINJFoPiw-5R0k/edit#heading=h.8klq5yujpzks
Plus the stuff already in the wiki/repo

**Comment by AlannaBurke** [comment]
Thank you! If there are any more links etc, please drop them here so I can find them :)

**Comment by agentrickard** [comment]
I put a sample bash script for building Drupal 8 on OS X into a gist.

https://gist.github.com/agentrickard/1caab0c9084b1ee1418c29f22969f260

**Comment by agentrickard** [comment]
And this script is how I run tests locally.

https://gist.github.com/agentrickard/888f9730d3cc0496b9846137c449bd53

You can also use core's `/core/scripts/run-tests.sh` which this script simply wraps for readability.

**Comment by sparklingrobots** [comment]
@zenlan explained how github is set up in the channel & several people found it useful: 
zenlan [4 hours ago] 
The issues and project boards are accessories to the repository

zenlan [4 hours ago] 
issues is where you report 'bugs', 'queries' etc. also just discussion

zenlan [4 hours ago] 
project boards where you can track the progress of projects that belong to the repository

zenlan [4 hours ago] 
the wiki is the documentation for the repository

**Comment by cleverington** [comment]
Just to toss notes for the aggregation later on "Up and Online for Development"

## Drupal OSX Example Setup Guide

Copied this one from a friend and have been trying to get it "up to par".

**Currently Missing:**
- Testing Tools (Selenium, JDK, PHPUnit, etc.)
- Drupal 8 Tools (WebProfiler, Devel, Drupal Console)
- Text-Editor Addons for Testing (Gherkin, Behat, etc.)
- Personal Access Keys
- Continuous Integration Toolkits (CircleCI integrations, Jenkins tools, etc.)
- Cheat Sheets (Drush, Behat, Drupal Console, Gherkin, etc.)
- Example Code (Drupal 7 Hooks, Gherkin Templates, pre/post_process functions, etc.)

https://github.com/cleverington/setup.environment

**Comment by laughnan** [comment]
Going to close this. We're moving all issues onto Drupal.org: https://www.drupal.org/project/issues/ddi_contrib
