### ISSUE TITLE
Backend test teams

### ISSUE THREAD

**Issue by zenlan** [drupaldiversity/contrib#19]
Based on this week's [ddi meeting](https://drupal.slack.com/archives/C76TQUQ2D/p1508865139000068) the proposal is to form teams of 2-3 people per issue, the following is a loose attempt to mix the levels of skill around in the teams. Feel free to make alternative proposals and of course to come up with more exciting team names.

- Team A
- - cboyden (mentor) PDT/PST
- - Nick Wilde (mentor) 
- - angelam (mentee) (CST)
- - sugaroverflow (mentee) (EST)
- Team B
- - agentrickard (mentor) EST (UTC+5)
- - mdrummond (mentee) CDT/CST
- - sparklingrobots (mentee) - PDT/PST
- - alexdmccabe (reviewer) - EDT/EST 
- Team C
- - zenlan (mentor) BST/GMT
- - michaellenahan (mentor) -  CEST/CET
- - laurarocks (mentee) - EEST (UTC +3)/EET
- - caralin (reviewer) CEST/CET

On hold: 
- - cleverington (mentee) -CDT/CST

**Comment by sparklingrobots** [comment]
I think caralin wanted to be a mentee & cleverington asked to be one as well after the meeting. I'm going to edit the main issue to reflect that.

**Comment by sparklingrobots** [comment]
I also added the roles people volunteered for so we can retain that info & make sure teams have at least one mentee & one mentor.

**Comment by zenlan** [comment]
I was thinking that rather than have dedicated reviewers, each team would review another teams work. The team can self-nominate a reviewer. To avoid teams reviewing their own work and to spread the task around. Team A review Team B, Team B review Team C etc.

**Comment by zenlan** [comment]
According to the slack thread, Caralin did not react to the proposal with a thumbs up but with a tick indicating that she would take a role as reviewer not mentee. I only went by what was posted in that thread, if there was another thread that Caralin mentioned being a mentee then I'm afraid I don't recall that.

**Comment by zenlan** [comment]
[post with the role reactions](https://drupal.slack.com/archives/C76TQUQ2D/p1508865412000136?thread_ts=1508865139.000068&cid=C76TQUQ2D)

**Comment by sparklingrobots** [comment]
@zenlan You are totally right; I made a mistake on what caralin signed up for! I also tried to stick to just the reactions on that post (plus cleverington's later post). 

I like your idea to rotate the reviews across teams.

**Comment by Caralin** [comment]
I signed up as reviewer to learn about how tests are written (and time issues on being a mentee on my side) - I find it a bit sad that I'm not in a team at all now since you changed the question form be mentor, mentee, reviewer/tester - to be mentor/mentee :(

I do like the idea of teams testing other teams test thought

**Comment by zenlan** [comment]
No problem Caralin, you can join my team and you can hop in to do stuff as and when you're able. The thread was a bit confusing but this is the perfect place to iron out the bumps.

**Comment by zenlan** [comment]
Something just occurred to me, issue of timezones and office hours. We can swap around a bit if issues arise with team members availability to each other. Waiting for hours for a review or help can be frustrating. It would be useful to know everyone's timezone.

I'm in London and its BST until next Sunday when its back to GMT. I have a lot of flexibility with office hours as a freelancer.  I find Slack very quiet during much of my daytime, it usually picks up in the late afternoon for me and it hits peak traffic near my bedtime.

**Comment by alexdmccabe** [comment]
I'm in Orlando, currently EST until Sunday, November 5, when it changes to EDT.

I work from 9 AM - 5 PM my time, but I'm on Slack during those hours.

**Comment by RainbowArray** [comment]
I'm in Minnesota, currently CST until Sunday, November 5, when it changes to EDT.

I'm roughly online during normal work hours in my time zone.

I think there could be value to getting folks in Europe into the same team for the sake of time zone synchronicity. Also fine with trying out the current teams to see how that goes.

**Comment by cleverington** [comment]
Texan here, CST.  Ick, is Daylight Savings coming...

I'm fine on times, but I feel we should *definitely* use Issues / Notes, because I tend to have big-thoughts outside of general meeting times. 😺

**Comment by LauraRocks** [comment]
I'm from Finland so EEST (UTC +3) and after next weekend EET. I can do stuff at evenings and also during the day I also have Slack open.

**Comment by Caralin** [comment]
Germany so UTC +2 = CEST and on 29.10. back to UTC +1 = CET

I have slack open but mostly can't work on stuff during work hours 

on time zones: wasn't there a tool/website where you can input a meeting time in your time zone, get a link and everyone can see the meeting time in their timezone? I think that would be helpful for meetings? I was late yesterday because I got confused on time zone math

**Comment by sparklingrobots** [comment]
@Caralin If there is such a thing I'd be happy to use it! I set the reminder to be 24hr in advance so that hopefully it will help with the math problem but I know that stuff gets complicated quick. 

Just updated the team lists above with the info folks have put in the thread. I *think* I know a few more but didn't want to get it wrong.

**Comment by michaellenahan** [comment]
I wanted to say hello, I was not able to make it to the slack meeting but was very interested to read it today!

With PHPUnit I am a bit rusty but I have written some. I'm experienced with Behat and some other test frameworks. So I could be a mentor, but one who may also need help sometimes from other mentors.

@Caralin I also live in Germany, in case it helps to form groups in more-or-less the same time zones.

**Comment by laughnan** [comment]
Going to close this. We're moving all issues onto Drupal.org: https://www.drupal.org/project/issues/ddi_contrib
