### ISSUE TITLE
Front-End Meeting Notes - 10/24

### ISSUE THREAD

**Issue by sacarney** [drupaldiversity/contrib#21]
[Agenda for 10/24 front-end meeting](https://github.com/drupaldiversity/contrib/issues/13)

This is a summary of discussion from the meeting. Please add anything I mischaracterized or forgot to include.

# Why build a theme?
* A theme shows a path for front-end developers to contribute
* A well-defined theme is a project well-suited to be an accessible entry point to contributing to, perhaps, more complex themes.
* Opportunity to push theming forward with newer things like components and CSS Grid.

# What are our priorities in building a theme?
* Accessible
* Good performance
* Best practices and standards compliant
* Easy-to-use for site builders

Generally agreed that a theme for the sake of getting experience building is a worthy cause on its own too.

# Who is the user? What is the scope of this theme?
This is tricky to nail down and needs more discussion, but...

* Build a blogging-centric theme with a non-coder site-builder in mind.
* Has a good design out of the box...
* ...but is ready for subtheming
* Sort of targeting the same users who would build with Wordpress's Twentyseventeen theme.
* Tara (aka sparklingrobots) has volunteered to be an example stakeholder. Sarah (sacarney) has also agreed to share what she thinks are good blog considerations.

* We want to limit the bells and whistles of theme customizations built in, but maybe have a few.

* Potential to fill the role of Bartik, as a thoroughly themed theme.

# Naming and Statement
We'll make an issue to decide on a name, and an issue to clearly define a scope

# Front-end Tech Tools
We discussed front-end technologies we'd like to work with including:

* Forgoing Bootstrap or other frameworks in favor for something custom with grid based on CSS Grid
* UI Patterns module would be great so people can focus on components without breaking each others' work. 

# Next meeting time
Thursday, November 2 at 11am PST in the #ddi-contrib-team Slack

**Comment by sacarney** [comment]
Front-end Devs: CSS framework discussion: https://github.com/drupaldiversity/contrib/issues/230

Design and stakeholders: Design notes: https://github.com/drupaldiversity/contrib/pull/20/commits/335903d0b5eb77077f441fc3406fb421b5d38bf7

**Comment by sparklingrobots** [comment]
Do you want me to ask in the main DDI channel meeting for volunteer stakeholders, or do we have enough?

**Comment by sacarney** [comment]
I think we can leave that to kfletcher, but with you, a little of me, and a little of mdrummond that may be as much as is helpful?

**Comment by sparklingrobots** [comment]
Ok, sounds good--I was thinking it could get to too many cooks in the kitchen pretty fast.  I will not do it, but the offer stands if it becomes helpful.

**Comment by LauraRocks** [comment]
I can be also of help here, as I am very customed to building smallish sites with D8 that could benefit from this theme.

**Comment by sparklingrobots** [comment]
I'm going to close this issue since the meeting is done!
