### ISSUE TITLE
Theme: Design brief 

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/contrib#29]
We need to create a design brief so we can make this awesome theme.

Some notes here: https://github.com/drupaldiversity/contrib/blob/master/meeting-notes/Design%20Notes

**Comment by sparklingrobots** [comment]
kefletcher said they would dig up an existing design brief and share it here! Hooray!

**Comment by keltique** [comment]
DDI-CONTRIB CREATIVE BRIEF QUESTIONNAIRE

Some of these may seem very abstract, but getting a fix about how you feel about your blogs and their goals, who you think your readers are and what they may want, and how you want your readers to feel about your blog, is important information to have, since a lot of what and how we want to convey this information with design is non-verbal and emotional in nature.

Most of these questions can be answered with short simple statements, with an eye towards the emotional as well as practical factors. 

There are no “correct” answers, only authentic ones. :)

**Who are you, the blog authors?**

- What are the specific Drupal topics you blog about?
- What is your unique value proposition to your readers?
- What makes your blogs different from any other blog in the Drupal blog space?
- How do you perceive your blogs current design style and what it says to your readers?
- Please list 5-8 individual adjectives that you think best describe your blogs, or how you would want people to feel about them.  (Feel free to be very abstract and touchy-feely with this part.)

**What promises do you want to make to your readers with your design?**

- What is the existing defined purpose or mission of your blog?
- How would you describe your values as a Drupalist in a short list of words?
- What are the long-term goals of your blog?
- Please supply a link to your existing blog.

**Who is your blog speaking to?**

- What kinds of readers do you currently serve?
- How did your current readers find you?
- What do know about how your existing readers currently perceive your blog?
- What are your blog readers most important needs?
- Are there any negative perceptions you want to try and counter, or specific perceptions to avoid?
- Please create 3-4 “user stories” about what needs and situations you imagine would cause readers to seek out your blog.
- Are there specific readers you want to reach, that you aren’t reaching right now?

**Who are your fellow Drupal bloggers in this space, and how do you stand out from them?**

- Please create a short list of similar blogs you feel serve the same readership you are trying to reach. _About 3 should be fine._
- What makes your blog a better choice for the reader than these?
- What does your Drupal blog offer that no other Drupal blog offers?
- What does your Drupal blog offer that every Drupal blog offers?


**Content**

- What kinds of content do you place in your blog? Original articles? Commentary on shared articles? Videos?

**Analytics**

- Analytics info on the sort of technology users use to view your blog.
- Analytics info on what pages of your blog are the most popular ones.
- Analytics info on most popular keyword searches that people use to find your blog.
- Analytics info on how people reach the site.  Organic search? Social media? Referral links? Paid search? (Useful for later when you want to effectively promote the blogs)

**Comment by vclewis** [comment]
@keltique thanks for your work here. The current plan is that @sparklingrobots @sacarney and @mdrummond will complete this by our team meeting next week (Thursday 11/16 at 11 am PT) so we have something to work off of for design decisions.

**Comment by sacarney** [comment]
**Who are you, the blog authors?**

- What are the specific Drupal topics you blog about? - Theming challenges and how-tos. How make a cool newsfeed with Bootstrap 4, for example.
- What is your unique value proposition to your readers? - It's not always easy to find front-end/theming focused documentation for Drupal 8, so I'd want to share that.
- What makes your blogs different from any other blog in the Drupal blog space? - Not sure
- How do you perceive your blogs current design style and what it says to your readers? - I use Medium right now. I like that it's clean, but it does not show anything personal about who I am.
- Please list 5-8 individual adjectives that you think best describe your blogs, or how you would want people to feel about them. - Easy, accessible, curious, experimental, bold

**What promises do you want to make to your readers with your design?** - I will try not assume any coding knowledge, and if I do, provide context so it's do-able for themers who aren't back-end developers.

- What is the existing defined purpose or mission of your blog? - Share what I'm learning and doing as a Drupal 8 themer.
- How would you describe your values as a Drupalist in a short list of words? - Good design works better. Drupal can look like anything.
- What are the long-term goals of your blog? - Continue to provide up-to-date resources on my experience theming.
- Please supply a link to your existing blog - https://medium.com/@sarahcodes

**Who is your blog speaking to?** - The poor abandoned drupal themers! 🌵 

- What kinds of readers do you currently serve? - I do not know if I even have any readers.
- How did your current readers find you? - ?? 
- What do know about how your existing readers currently perceive your blog? =??
- What are your blog readers most important needs? - ??
- Are there any negative perceptions you want to try and counter, or specific perceptions to avoid? - That Drupal 8 theming is not as easy as Wordpress and that Drupal 8 isn't for designers/themers
- Please create 3-4 “user stories” about what needs and situations you imagine would cause readers to seek out your blog.
-- I am trying to do a specific thing, like style buttons, but I can't figure out how
-- I want to make my Views look cool but don't know how to control the mark-up to work with my existing design.
-- Other tutorials assume I know Drupal 7 or php

- Are there specific readers you want to reach, that you aren’t reaching right now? - ??

**Who are your fellow Drupal bloggers in this space, and how do you stand out from them?**

- Please create a short list of similar blogs you feel serve the same readership you are trying to reach. - ?
- What makes your blog a better choice for the reader than these? - I have a hard time finding front-end dev focused Drupal 8 documentation. It all seems much closer to the back-end of front-end...
- What does your Drupal blog offer that no other Drupal blog offers? - Specific how-tos that try not to assume lots of coding knowledge
- What does your Drupal blog offer that every Drupal blog offers? - ??

**Content**
What kinds of content do you place in your blog? Original articles? Commentary on shared articles? Videos? - Original articles that show how I did something.

**Analytics**
I have an average of 10 reads on my articles, total. So not well trafficked.

**Comment by sparklingrobots** [comment]
**SPARKLINGROBOTS' RESPONSES**

**Who are you, the blog authors?**
I’m Tara.  I have a LOT of interests and this blog is where I let them all mix together.  I arrived in the Drupal-sphere from a start in print design, that led to site building, that led to front end, that led to backend. 

I’m 34, live in Los Angeles, CA but have lived long stretches in Minnesota & New Mexico.  

I am planning to meld two different blogs I’ve written over the past 4 years or so—one that was meant as a sales/client education blog, and one that is far more personal. 

**What are the specific Drupal topics you blog about?**
I want to pre-confess that my blog is like 10% drupal 20% general web/tech, and 70% weird other stuff. 

I used to blog a lot about high-level questions for arts orgs looking to get a website done. Occasionally I will post something pretty technical. Lately I’ve been wanting to write more about lessons learned from the DDI book club, DDI mentoring, etc. My big content buckets are: 
—Creative Writing (poetry & some fiction)
—Web Development 
—Travel 
—Being a good person (diversity & inclusion issues, environmentalism, personal & civic engagement, bicycling)

**What is your unique value proposition to your readers?**
I have a pretty broad ranging background in development and am totally self-taught. So I think I’m pretty good at solving things in a humble yet funny way. Also I’m a queer woman and that’s just sort of unique. 

**What makes your blogs different from any other blog in the Drupal blog space?**
I try very hard to explain things I don’t see anybody else explaining.  I try also to share my own frustration so people can have a sense of camaraderie. 

**How do you perceive your blogs current design style and what it says to your readers?**
I use Danny Englander’s Gratis theme for this blog.  I think the only things I customized are the typeface and maybe the colors. Added some custom image fields and then got really lazy with them. 

I perceive the design as minimal, focused on the writing, and a bit quirky. I imagine it says that I’m focused on the work but willing to be a bit weird. 

**Please list 5-8 individual adjectives that you think best describe your blogs, or how you would want people to feel about them. (Feel free to be very abstract and touchy-feely with this part.)**
Vulnerable
Kind
Encouraging
Insightful
Artistic

**What promises do you want to make to your readers with your design?**
EEEEK promises!! 

I promise that I am a human. (Which I take very seriously.  I promise to be authentic and perhaps unpredictable, but never overly polished or corporate.)

**What is the existing defined purpose or mission of your blog?**
Literally the current purpose of my blog is: “No strategy”.  In the very first post I wrote: 
> So, here we are. You, whoever you are, and me. I don't want to play games with buzzfeed lists or wordcount or what's above the fold. I want to write well on things that interest me, and until I get good at that, I want to write often on things that interest me.
> No strategy. No games. Writing. Indulging. Producing.
(Link: http://www.tara-king.com/blog/genesis-blog)

**How would you describe your values as a Drupalist in a short list of words?**
Open source. Diverse & inclusive.  Friendly. 

**What are the long-term goals of your blog?**
Long term goals of my life are to make writing a more central part of my life.  So the blog will be a big part of that.  I’d like to start a Patreon eventually

**Please supply a link to your existing blog.**
Current: http://www.tara-king.com/
Archived but likely to partially get rolled into this migration: http://sparklingrobots.com/blog (sorry for the houndstooth)

**Who is your blog speaking to?**
People with broad ranging interests, but also people with specific interests in Drupal, creativity, travel, etc. 

**What kinds of readers do you currently serve?**
They tend to be women (probably 65%), between 30 & 40.

**How did your current readers find you?**
Largely they are my friends/colleagues/former clients. This post turns up in google a fair amount: sparklingrobots.com/blog/how-install-drush-dreamhost-shared-server
 What do know about how your existing readers currently perceive your blog?
Not much. I get occasional feedback on twitter. One friend called me a badass of self growth and I feel like that’s probably about right. 
 **What are your blog readers most important needs?**
They either need/want to find out what I’m up to, or they’re searching for help on a specific problem. 

 **Are there any negative perceptions you want to try and counter, or specific perceptions to avoid?**
I’m not interested in looking corporate or “professionalized”.  I want the blog to look good and to be professional, without that sheen of “I’m faking it for appearances”. 

 **Please create 3-4 “user stories” about what needs and situations you imagine would cause readers to seek out your blog.**

* I am stuck on this simpleSAML authentication problem and I googled “oh god help me kill simplesaml” and found this friendly blog that helped me solve my problem (though it did not help me kill simpleSAML). 
* I googled “travel in Morocco for genderqueer folks”.
* I went to this conference/convention and wanted to read a recap.
* I know Tara and want to find out what she is doing.
 Are there specific readers you want to reach, that you aren’t reaching right now?
I don’t know but would love to find out. 
 Who are your fellow Drupal bloggers in this space, and how do you stand out from them?
Unsure. 

**Please create a short list of similar blogs you feel serve the same readership you are trying to reach. About 3 should be fine.**
* Stackoverflow is not a blog and I have no goals to replace it but I feel like the kinds of questions I answer are also answered there.
* ???

**What makes your blog a better choice for the reader than these?**
I’m funnier.

**What does your Drupal blog offer that no other Drupal blog offers?**
A bit more humility and open acknowledgement of the frustration (instead of just “here’s the answer”). And lots of non-drupal content. 

**What does your Drupal blog offer that every Drupal blog offers?**
Drupal howtos, Drupalcon recaps

**Content**

**What kinds of content do you place in your blog? Original articles? Commentary on shared articles? Videos?**
Original articles, how-tos, poems (eventually). 

**Analytics**

**Analytics info on the sort of technology users use to view your blog.**
78% desktop, 21% mobile.  35% Chrome, 35% Firefox (the rest is misc). 

**Analytics info on what pages of your blog are the most popular ones.**
http://www.tara-king.com/blog/year-4-lessons-learned
http://sparklingrobots.com/content/8-tips-successful-diy-artist-retreat
http://sparklingrobots.com/blog/how-install-drush-dreamhost-shared-server
http://sparklingrobots.com/blog/how-much-does-artist-website-cost-anyway

**Analytics info on most popular keyword searches that people use to find your blog.**
“Tara king”
how to start an artist retreat	
install it or recompile php without --disable-phar	

**Analytics info on how people reach the site. Organic search? Social media? Referral links? Paid search? (Useful for later when you want to effectively promote the blogs)**
50% direct, 45% organic search. It’s likely social media—lots more people find it when I actively direct them to it than any other way.

**Comment by laughnan** [comment]
⚠️ Looking to getting this ported to https://www.drupal.org/project/ddi_contrib in the near future

**Comment by laughnan** [comment]
Going to close this. We're moving all issues onto Drupal.org: https://www.drupal.org/project/issues/ddi_contrib
