### ISSUE TITLE
Theme: Decision-making process 

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/contrib#30]
Do we want a front-end lead where people can always suggest whatever they want, but if there’s a disagreement, somebody needs to eventually make a call to keep things going forward.

Alternatively: After some discussion, call for a decision, account for votes, and then go for it. But someone can also say, hold up! Anyone can say, Let's Make a Decision Now. Anyone can be like ummm no, more discussion needed. Voting requires good timeboxing rather than just who is around at any given moment when a decision is being made.

We can use slack to poke for input and see if it's a good process for our small team? Can also revise as needed.

**Comment by sparklingrobots** [comment]
Can the "Let's make a decision now" happen in GH? Or only in Slack?

Someone says “it’s time to make a decision” in GH, and then we have a pre-determined time box for voting/input, and at the end of that time, we make the decision.

Are github's notifications comparable to Slack's? Or can we set up an integration so this channel gets notified when there's an issue that needs deciding in GH?

The one thing that is in my mind re: these timeboxed decisions is this: The reason a lot of people give for women/minorities not contributing is lack of time.  I don’t want to build a system for contributing that is putting too much time pressure on people.

**Comment by sacarney** [comment]
I think the observation that time-boxing decision making can exclude people who have less time. I certainly don't want that.

Slack is a very fast-moving channel, so things can be missed. I think decisions should happen here in github.

As far as how long we allow for input once someone has said Hey Let's Make A Decision, I think perhaps that can be fluid? We can perhaps use Slack to notify relevant voices that we're hoping to make a move on a decision, and then wait? Weekly meetings may be a good interval. We publicize them well, they're well documented, and it seems like for most of us it's our dedicated time to think about this project? So maybe at least a week? 

Example: 
1. Github: Good discussion, let's make a decision.
2. Hey @ name @ name @ name and anyone else, any input?
3. *Add to next meeting's agenda.*
4. At next meeting - hey look, we're making a decision.
4. Next meeting, make the decision. 

Just brainstorming.

**Comment by laughnan** [comment]
⚠️ Looking to getting this ported to https://www.drupal.org/project/ddi_contrib in the near future

**Comment by laughnan** [comment]
Going to close this. We're moving all issues onto Drupal.org: https://www.drupal.org/project/issues/ddi_contrib
