### ISSUE TITLE
Create a list of issues tagged or otherwise maintained for our team.

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/contrib#32]
@agentrickard suggested that we maintain a list of issues for our team, either by tagging on d.o or as a list.  

- Tagging might not work b/c sometimes people remove tags. We might be able to get a new tag added by d.o. webmasters
- For now we can create a list of good issues to start on in GH. (caralin's idea)

As the mentees are still getting up to speed on patching/testing basics, this seems like a good task for mentors to figure out a system for tracking issues as we work and perhaps to triage a few for us to start with.

**Comment by agentrickard** [comment]
It's a bit redundant, but we can always dual-track issues in GitHub and d.o. That gives us a more permanent record and potential dashboard of issues that we control.

We could do the same with triaged issues. Make an issue here on GitHub, link to the d.o. ticket and mark as "good first issue" or some other tag.

**Comment by laughnan** [comment]
Going to close this. We're moving all issues onto Drupal.org: https://www.drupal.org/project/issues/ddi_contrib
