### ISSUE TITLE
Follow up on Examples module test questions.

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/contrib#33]
A) create issue plan/query on d.o; 
B) @mdrummond goes undercover for the lowdown; 
C) A+B good responses we dive into the examples module; 
D) A/B duff responses we abandon ship and start our own examples module yaaarrrr 

I'm assigning @zenlan since she's been most active on this--hope that's okay! If not, unassign yourself! 💃

**Comment by zenlan** [comment]
Step 1: Read up on existing issues, roadmap, policies and project goals.

[Examples module](https://www.drupal.org/project/examples )
[Comaintainer practices and procedures](https://www.drupal.org/node/1007276 )

Step 2: Select recent issues that are doable

[Make gender more inclusive](https://www.drupal.org/node/2898380)
[Update content of testing_example](https://www.drupal.org/node/2900144)
[Inconsistent capitalization in module name / menu links](https://www.drupal.org/node/2831282)
[Rethink the form examples](https://www.drupal.org/node/2319591)

Step 3: Formulate a post that a) introduces the group, b) states our case and c) asks specific questions, e.g.

>I'm posting on behalf of the ddi-contrib group, a team of Drupalers who have come together with a goal of immersing ourselves in the contribution process as learners and mentors.

>We were scouting for a place to start and agreed that the Examples module is an excellent resource and that the 8.x branch would benefit from some contribution. We are particularly interested in practising writing good tests.

>We have read the goals on the project page and the [Comaintainer practices and procedures](https://www.drupal.org/node/1007276 ) advice (not that we are asking for comaintainer status) and looked through the issue queues.

>We would like to know... 
__WHAT IS OUR QUESTION?__ 
**Are you OK with us doing this? Do you have advice or a perhaps a priority you'd like us to start with? Should all communication happen in the issue queue or is there a backchannel that we should use?** __COULD USE SOME HELP HERE__

**Comment by michaellenahan** [comment]
The text from Step 3 above is very good!

One nit-pick I would have is that we should say where the discussions take place.

> I'm posting on behalf of the ddi-contrib group, a team of Drupalers who have come together with a goal of immersing ourselves in the contribution process as learners and mentors.

Something roughly like this:

> We can be found on https://drupal.slack.com under "ddi-contrib-team". We also have a github account https://github.com/drupaldiversity where we track our team issues. (See for example https://github.com/drupaldiversity/contrib/issues/33 - this is where we discussed our approach to the examples module).

Apart from that I think it's really good. It is respectful and to-the-point.

EDIT - we should also include the list of issues we intend to look at and work on (from Step 2) in the text of the issue-queue issue.

So, I guess eventually the next step is to post the text from Step 3 above into the examples module's issue queue?

**Comment by zenlan** [comment]
Thanks Michael! Good suggestions there, especially as I saw WebChick in channel advising to get off the island and promote the team profile.

I would link to the [contrib group's repo](https://github.com/drupaldiversity/contrib) rather than the whole account and I think we could enhance the README to include some of our technical profile/goals  alongside the general text there.

I'd like to get some more team members' input before posting, but ready to roll any time. What do people think of those issues? Any other suggestions? Anyone like to add to the repo README?

**Comment by sparklingrobots** [comment]
> We would like to know...
> WHAT IS OUR QUESTION?
> Are you OK with us doing this? Do you have advice or a perhaps a priority you'd like us to start with? Should all communication happen in the issue queue or is there a backchannel that we should use? COULD USE SOME HELP HERE

In this case, I think we could refer to the conversation @mdrummond had with them, something like: 

> We know you had a brief conversation with Marc Drummond about this and would like to follow up and get our next steps in order. Our original plan was to deprecate the simple_test examples and add in phpunit test examples, though it sounded like you were planning some work on this already and we don't want to conflict.   Should we 
> 
> We're available in #ddi-contrib-team on Drupal slack if that's easier--you can ping me (@zenlan) to sort it out. 

Before sending that, I'd like @mdrummond to jump in in case I've mischaracterized the response--it's lost to the slack backscroll now so I am working from memory.

**Comment by sparklingrobots** [comment]
Overall, though, I really like this as a way of getting started on a given issue/project. 

I second your suggestion that we improve the README in our repo, though I don't think that needs to hold us up on this particular task.

**Comment by RainbowArray** [comment]
"We know you had a brief conversation with Marc Drummond about this and would like to follow up and get our next steps in order. Our original plan was to deprecate the simpletest_examples and add in phpunit test examples, though it sounded like you were planning some work on this already. We understand from that conversation that the plan is to move the content in simpletetest_examples and phpunit_examples into the content in the testing_examples module. We also understand that some of the testing_examples content is connected with drupalize.me content, and we're reaching out to the drupalize.me team to find out more about that. Is there anything else we should know before we start working on issues? Any priorities you have on what to move over, anything we should try to steer clear of? Also, our assumption is that we should try to keep communications within the issue queues, but if there are any backhannels we should be aware of—a Slack channel for example—that would be great to know."

FYI, I reached out to Blake at drupalize.me, he thinks this sounds great that we're going to work on this and doesn't think there would likely be any conflicts, but we're going to try to talk Friday, where we can get more of the lowdown.

**Comment by zenlan** [comment]
Unless anyone has anything else to add, I'll post this on d.o later. Thanks for the contributions. :) 

>I'm posting on behalf of the ddi-contrib group, a team of about a dozen back-end Drupalers who have come together with a goal of immersing ourselves in the contribution process as learners and mentors. 

>We were scouting for a place to start and agreed that the Examples module is an excellent resource and that the 8.x branch would benefit from some contribution. We are particularly interested in practising writing good tests.

>We have read the goals on the project page and the [Comaintainer practices and procedures](https://www.drupal.org/node/1007276 ) advice (not that we are asking for comaintainer status) and looked through the issue queues.

>A few things in the issue queue caught my eye as possible starting points...
[Make gender more inclusive](https://www.drupal.org/node/2898380)
[Update content of testing_example](https://www.drupal.org/node/2900144)
[Inconsistent capitalization in module name / menu links](https://www.drupal.org/node/2831282)
[Rethink the form examples](https://www.drupal.org/node/2319591)

>One of our team mates had a brief conversation with you about this and gleaned that the roadmap includes deprecating simpletetest_examples and phpunit_examples in favour of the testing_examples sub-module.  

>Is there anything else we should know before we start? Any priorities or advice? 

>We would like to keep communication as open as possible - within the issue queues - but if there are any useful backchannels we should be aware of, e.g. Slack or IRC, that would be great to know.

>We can be found on Slack in the [ddi-contrib team channel](https://drupal.slack.com/messages/C76TQUQ2D/). We also have a [github repo](https://github.com/drupaldiversity/contrib) where we track our team issues. (See for example #33 - this is where we discussed our approach to the examples module).

**Comment by zenlan** [comment]
Work and weekend activities overtook my plan to post this on Friday but its up now at https://www.drupal.org/project/issues/examples/2922966

**Comment by sparklingrobots** [comment]
Woohoo!! I'm going to close this ticket, then--though happy to reopen if I'm being overzealous.
