### ISSUE TITLE
Expand documentation on server environment set-up.

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/contrib#34]
Documentation for getting set up could be improved (e.g. Suggestions for a server environment a la Dev Desktop or VirtualBox.)

I got a bit lost at that step and want to work on it a bit.

**Comment by sparklingrobots** [comment]
I also want to add this link to our resources, and perhaps just put a link or other big obvious flashing sign to *where* our resources are. 

http://drupal.org/tools

**Comment by kclarkson** [comment]
Here are two different docker container tools that are being used by the community. 
- Lando https://docs.devwithlando.io/tutorials/drupal8.html
- Docksal http://docksal.readthedocs.io/en/master/

**Comment by laughnan** [comment]
Going to close this. We're moving all issues onto Drupal.org: https://www.drupal.org/project/issues/ddi_contrib
