### ISSUE TITLE
Theme: Pattern Lab?

### ISSUE THREAD

**Issue by sacarney** [drupaldiversity/contrib#37]
Here is Pattern Lab! Many of us are excited to work with Pattern Lab.

http://patternlab.io/

Let's talk about Pattern Lab!

**Comment by keltique** [comment]
I found this class i took at GovCon super useful- its well enough documented that you can run yourself thru it, pretty easily. https://github.com/forumone/component-based-theming

**Comment by cleverington** [comment]
Not part of the FE team, but.....

There are two popular Pattern Lab Drupal 8 themes which could potentially be used as 'parents' for the group, in case people have not seen them:

## Four Kitchens' *Emulsify*
- https://github.com/fourkitchens/emulsify
- Tutorial / Intro: https://www.youtube.com/watch?v=s9RXB9QbgUs

## Phase2's *Dashing*
- https://github.com/phase2/pattern-lab-starter
- https://github.com/phase2/drupal-lab
- Intro: https://www.phase2technology.com/blog/introducing-pattern-lab-starter-8 

Even if ya'll go completely off-rails, these at least give a point to start.

**Comment by laughnan** [comment]
⚠️ Looking to getting this ported to https://www.drupal.org/project/ddi_contrib in the near future

**Comment by laughnan** [comment]
Going to close this. We're moving all issues onto Drupal.org: https://www.drupal.org/project/issues/ddi_contrib
