### ISSUE TITLE
Tools to Cover in 11/16 Front-End Meeting

### ISSUE THREAD

**Issue by vclewis** [drupaldiversity/contrib#38]

**Comment by LauraRocks** [comment]
Just throwing some ideas based on what I am working with right now:

Gulp vs Grunt 
Autoprefixer (gulp-autoprefixer?)
Browser-sync
Libsass, node-sass, gulp-sass?
Breakpoint-sass
jshint?
linting?
gulp-plumber and other like that
gulp-concat

**Comment by kclarkson** [comment]
- We could use foundation or other base themes as an example of what are a good set of tools. 
- Also depending on what local environment we decide could help alleviate conflicting versions of tools already installed on a local machine. Such tools as: Lando or Docksal.

**Comment by LauraRocks** [comment]
Yes, I think some of those are used at least in Radix starter theme. In css framework issue I listed these themes as an example (quick scrape through d.o) where we could bechmark our tools: 

https://www.drupal.org/project/basic
https://www.drupal.org/project/fortytwo
https://www.drupal.org/project/cog
https://www.drupal.org/project/radix
https://www.drupal.org/project/twentyseventeen

Haven's look at foundation, but I think it would very good as well.

**Comment by LauraRocks** [comment]
As for the local environment, that's a very good issue as well! I actually don't know what the practice is, I usually run the tools in theme folder, and haven't come across any conflict problems... I know that you should/could (?) run them in the "root project folder", but then it would definitely depend on the local environment, right? This is very my knowledge and skills are very very thin, but I'm very happy to learn...

**Comment by laughnan** [comment]
Closing this post-meeting. It's been moved to "Done" in our Project.
