### ISSUE TITLE
Collecting Ideas for a future Blog Distro based on the theme.

### ISSUE THREAD

**Issue by keltique** [drupaldiversity/contrib#39]

**Comment by kclarkson** [comment]
1. Phase I - MVP

- Define Required content types
  - Article
  - Landing Page 
  - Slideshow / Hero
- Layout
  - Layout Plugin 
- Views
  - Blog Page
  - Taxonomy

**Comment by LauraRocks** [comment]
This is a very interesting topic as well, thank you for opening the discussion! I was wondering what we _could_ do with only the theme. There are two views, front page and taxonomy term page in vanilla, could those be themed to achieve some of this? Of course when the design process evolves, we know better what needs to be done, but just thinking about the basics of what we could do.

**Comment by laughnan** [comment]
Going to close this. We're moving all issues onto Drupal.org: https://www.drupal.org/project/issues/ddi_contrib
