### ISSUE TITLE
Write session proposal for DrupalCon Nashville. 

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/contrib#46]
> mdrummond [40 minutes ago] 
> If we can do a session, it would really be great. I think that’s part of the value of this. Both to help a wider range of people to contribute and by contributing, showing to the wider Drupal community just one of the benefits of focusing on D&I work for the community.
> 
> mdrummond [40 minutes ago] 
> We don’t want to imply that this is transactional. Drupal should support D&I because it’s the right thing to do. But it’s cool if as a bonus, we get more people contributing. :slightly_smiling_face:

mdrummond offered to set up a google doc for collaborating on this. 

Deadline for DC Nashville is January 17.

**Comment by sparklingrobots** [comment]
Just a note: sugaroverflow & yesct are the track chairs on this. Sugaroverflow has definitely offered to chat with people about their session ideas, so let's run this by her to make sure we have a strong proposal!

**Comment by laughnan** [comment]
Going to close this. We're moving all issues onto Drupal.org: https://www.drupal.org/project/issues/ddi_contrib
