### ISSUE TITLE
Create a 'how-to' guide for leaving comments on drupal.org.

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/contrib#47]
laurarocks writes: "It just occurred to me that during Vienna sprint day, it was really helpful when somebody directed/mentored me how I should put my words in the reply to the issue queue. It’s really more intimidating that I thought."  We could also have some suggestions for how we present ourselves in the issue queues as well.

**Comment by agentrickard** [comment]
Some resources:

* [Panopoly contributor guide](https://docs.google.com/document/d/1nDCdblpTLPqc-oyCppGQ_FCHkkCs0MQn828VqeSh1vc/edit)
* [Drupal.org Issue Queue guide for helping maintainers](https://www.drupal.org/node/383956)
* [Drupal.org issue etiquette](https://www.drupal.org/node/1839650)
* [Views bug sqaud handbook](https://www.drupal.org/node/945414)

**Comment by laughnan** [comment]
Going to close this. We're moving all issues onto Drupal.org: https://www.drupal.org/project/issues/ddi_contrib
