### ISSUE TITLE
Create a google calendar to share our meeting times. 

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/contrib#48]

**Comment by laughnan** [comment]
Let me know if you want me to coordinate/handle this @sparklingrobots

**Comment by sparklingrobots** [comment]
@laughnan That would be great!! I just wanted to get our front end, back end and all-group meetings somewhere other than in my head. :) 

This page has team meeting times: https://github.com/drupaldiversity/contrib/wiki/Teams-&-Members

Full group meetings are on the first Mondays of the month at 10 am PDT (although January's will be on the second Monday of the month).

**Comment by laughnan** [comment]
Does this work @sparklingrobots?

https://calendar.google.com/calendar/embed?src=acreative.io_0917r07ben68pqct80uj9qoah0%40group.calendar.google.com

**Comment by sparklingrobots** [comment]
Woohoo!! Looks fantastic. Thank you, @laughnan!
