### ISSUE TITLE
Promotions at Florida DrupalCamp

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/contrib#50]
alexdmccabe [1:06 PM] I brought up the idea of mentioning ddi-contrib in the #florida channel and it seems like they're open to suggestions on how to promote it. A flyer in the swag bags, maybe an announcement during the opening talk? What do y'all think?

mdrummond [1:07 PM]  I think as long as it’s clear that this is not just mentoring for all. That this is a targeted effort at working on helping people in marginalized groups and those interested in supporting that effort.

Event is Feb 16-18, so we need to get this together by early February.

**Comment by laughnan** [comment]
Going to close this. We're moving all issues onto Drupal.org: https://www.drupal.org/project/issues/ddi_contrib
